#!/usr/bin/env python3
from __future__ import annotations
import re
import json
from pathlib import Path
from scripts._common import ROOT, OUTPUT_DIR, write_json, utc_now_iso

def slugify(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "episode"

def main() -> None:
    episodes_public = ROOT / "frontend" / "public" / "episodes"
    episodes_public.mkdir(parents=True, exist_ok=True)

    script_path = OUTPUT_DIR / "episode_script.txt"
    audio_path = OUTPUT_DIR / "episode_audio.mp3"
    video_path = OUTPUT_DIR / "episode_video.mp4"
    meta_path = OUTPUT_DIR / "episode_meta.json"

    if not (script_path.exists() and audio_path.exists() and video_path.exists()):
        raise SystemExit("Missing episode output files (script/audio/video). Run generation first.")

    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    title = meta.get("title") or "Daily AI News"
    date = meta.get("date") or utc_now_iso()[:10]
    slug = meta.get("slug") or f"{date}-{slugify(title)}"

    ep_dir = episodes_public / slug
    ep_dir.mkdir(parents=True, exist_ok=True)

    # copy files
    (ep_dir / "episode.txt").write_text(script_path.read_text(encoding="utf-8"), encoding="utf-8")
    (ep_dir / "episode.mp3").write_bytes(audio_path.read_bytes())
    (ep_dir / "episode.mp4").write_bytes(video_path.read_bytes())

    episode_json = {
        "id": slug,
        "date": date,
        "title": title,
        "description": meta.get("description") or "Generated by TV.RUSLANMV AI Pipeline",
        "created_at": utc_now_iso(),
        "video_url": f"/episodes/{slug}/episode.mp4",
        "audio_url": f"/episodes/{slug}/episode.mp3",
        "script_url": f"/episodes/{slug}/episode.txt",
        "meta": meta,
    }
    write_json(ep_dir / "episode.json", episode_json)

    # update latest.json and index.json
    write_json(episodes_public / "latest.json", episode_json)

    # append to index
    index_path = episodes_public / "index.json"
    index = {"updated_at": utc_now_iso(), "episodes": []}
    if index_path.exists():
        try:
            index = json.loads(index_path.read_text(encoding="utf-8"))
        except Exception:
            index = {"updated_at": utc_now_iso(), "episodes": []}

    eps = index.get("episodes", [])
    eps = [e for e in eps if e.get("id") != slug]
    eps.insert(0, {"id": slug, "date": date, "title": title, "video_url": episode_json["video_url"]})
    index["episodes"] = eps[:50]
    index["updated_at"] = utc_now_iso()
    write_json(index_path, index)

    print(f"✅ Published episode -> frontend/public/episodes/{slug}")

if __name__ == "__main__":
    main()
