#!/usr/bin/env python3
"""
Upload video to YouTube
"""
import os
import sys
import json
from pathlib import Path
from datetime import datetime
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload


OUTPUT_DIR = Path("output")


def get_youtube_service():
    """Create YouTube API service"""
    credentials = Credentials(
        token=None,
        refresh_token=os.getenv("YOUTUBE_REFRESH_TOKEN"),
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.getenv("YOUTUBE_CLIENT_ID"),
        client_secret=os.getenv("YOUTUBE_CLIENT_SECRET")
    )
    
    return build('youtube', 'v3', credentials=credentials)


def upload_to_youtube():
    """Upload video to YouTube"""
    print("=" * 70)
    print("📤 YouTube Upload for TV.RUSLANMV.COM")
    print("=" * 70)
    
    # Check video file
    video_file = OUTPUT_DIR / "episode_video.mp4"
    if not video_file.exists():
        print(f"❌ Video file not found: {video_file}")
        sys.exit(1)
    
    # Load metadata
    metadata_file = OUTPUT_DIR / "episode_metadata.json"
    if metadata_file.exists():
        with open(metadata_file, 'r') as f:
            metadata = json.load(f)
    else:
        metadata = {}
    
    # Video details
    today = datetime.now().strftime("%Y-%m-%d")
    title = f"📺 Daily AI & Tech News - {today} | TV.RUSLANMV.COM"
    
    description = f"""Daily AI and technology news delivered in 10 minutes.

🎯 In Today's Episode:
- Latest AI developments and breakthroughs
- Trending packages and developer tools
- Research papers and industry news

🤖 Generated by: {metadata.get('generated_by', 'AI')}
🗓️ Date: {today}
⏱️ Duration: {metadata.get('duration', 'N/A')} seconds

📺 Subscribe for daily AI news: https://tv.ruslanmv.com
🔗 MCP Protocol available for AI agents

#AI #MachineLearning #Tech #DailyNews #Automation
"""
    
    tags = [
        "AI", "Artificial Intelligence", "Machine Learning",
        "Tech News", "Daily News", "Automation",
        "Python", "Programming", "Software Development"
    ]
    
    # Upload settings
    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': tags,
            'categoryId': '28'  # Science & Technology
        },
        'status': {
            'privacyStatus': os.getenv('YOUTUBE_PRIVACY_STATUS', 'public'),
            'selfDeclaredMadeForKids': False
        }
    }
    
    print(f"\n📹 Video: {video_file}")
    print(f"📝 Title: {title}")
    print(f"🔒 Privacy: {body['status']['privacyStatus']}")
    
    try:
        print("\n🚀 Starting upload...")
        
        youtube = get_youtube_service()
        
        media = MediaFileUpload(
            str(video_file),
            chunksize=-1,
            resumable=True,
            mimetype='video/mp4'
        )
        
        request = youtube.videos().insert(
            part=','.join(body.keys()),
            body=body,
            media_body=media
        )
        
        response = request.execute()
        
        video_id = response['id']
        video_url = f"https://www.youtube.com/watch?v={video_id}"
        
        print(f"\n✅ Upload successful!")
        print(f"   Video ID: {video_id}")
        print(f"   URL: {video_url}")
        
        # Save YouTube info
        youtube_info = {
            'video_id': video_id,
            'url': video_url,
            'title': title,
            'uploaded_at': datetime.now().isoformat(),
            'privacy': body['status']['privacyStatus']
        }
        
        info_file = OUTPUT_DIR / "youtube_info.json"
        with open(info_file, 'w') as f:
            json.dump(youtube_info, f, indent=2)
        
        print(f"   Info saved: {info_file}")
        print("\n✅ SUCCESS: YouTube upload complete!")
        
        return video_url
        
    except Exception as e:
        print(f"\n❌ Upload error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    upload_to_youtube()
